name: grocery_list_2
description: A grocery list supports adding items, editing items, and deletion.
environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_bloc: ^8.0.0
  shared_preferences: ^2.2.0
  disposing: ^1.0.3+1

flutter:
  uses-material-design: true
dev_dependencies:
  flutter_lints: ^2.0.2
